proxy:
  title: Shiny Proxy Apps
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-wait-time: 200000
  authentication: simple
  admin-groups: admins
  users:
    - name: jack
      password: password
      groups: admins
    - name: jeff
      password: password
      groups: math
  docker:
    internal-networking: false
    url: http://localhost:2375
    port-range-start: 20000
  specs:
    - id: 01_dashboard
      display-name: Ddash
      description: Application which displays the dashboard of staircase survey
      container-cmd: ["Rscript", "dashboard_survey.R", "/home/testdt.txt"]
      container-image: localhost/dashboard_rminimal:0.03b
      container-volumes: ["/home/user6/Documents/git_repos/dashboard_survey/testdt.txt:/home/testdt.txt"]
logging:
  file: shinyproxy.log
